language: shell
matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      compiler:
        - gcc

      cache: ccache
      before_script:
        - >
          sudo apt-get install default-jdk default-jdk-headless default-jre default-jre-headless 
          python2.7-dev libpython2.7-dev libssl1.0.0 zlib1g zlib1g-dev libssl-dev libusb-1.0-0 
          libusb-1.0-0-dev libdbus-1-3 libdbus-1-dev libbluetooth3 libbluetooth-dev zlib1g zlib1g-dev 
          python-numpy python-setuptools python-wheel git cmake-qt-gui g++ make libboost-all-dev autoconf 
          automake libtool bison libpcre3-dev python3-dev python3-numpy python3-setuptools python3-wheel 
          mono-devel -qq
        - | 
            (
            rm -rf swig_build_dir
            mkdir -p swig_build_dir
            cd swig_build_dir
            curl -L http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz --output swig-4.0.1.tar.gz
            tar xf swig-4.0.1.tar.gz
            cd swig-4.0.1
            ./configure
            make
            sudo make install
            )
      env:
        - >
          RR_CMAKE_EXTRA_ARGS="-DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON3_EXECUTABLE=/usr/bin/python3.5 -DBUILD_PYTHON=ON -DBUILD_PYTHON_WHEEL=ON -DBUILD_JAVA=ON -DBUILD_NET=ON"
        - RR_CMAKE_GENERATOR="Unix Makefiles"
  include:
    - os: linux
      sudo: required
      dist: bionic
      before_script:
        - >
          sudo apt-get install default-jdk default-jdk-headless default-jre default-jre-headless 
          python2.7-dev libpython2.7-dev libssl1.0.0 zlib1g zlib1g-dev libssl-dev libusb-1.0-0 
          libusb-1.0-0-dev libdbus-1-3 libdbus-1-dev libbluetooth3 libbluetooth-dev zlib1g zlib1g-dev 
          python-numpy python-setuptools python-wheel git cmake-qt-gui g++ make libboost-all-dev autoconf 
          automake libtool bison libpcre3-dev python3-dev python3-numpy python3-setuptools python3-wheel
          mono-devel -qq
        - | 
            (
            rm -rf swig_build_dir
            mkdir -p swig_build_dir
            cd swig_build_dir
            curl -L http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz --output swig-4.0.1.tar.gz
            tar xf swig-4.0.1.tar.gz
            cd swig-4.0.1            
            ./configure
            make
            sudo make install
            )
      env:
        - >
          RR_CMAKE_EXTRA_ARGS="-DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON -DBoost_USE_STATIC_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON3_EXECUTABLE=/usr/bin/python3 -DBUILD_PYTHON=ON -DBUILD_PYTHON_WHEEL=ON -DBUILD_JAVA=ON -DBUILD_NET=ON -DPACKAGE_SWIG_SOURCE_ALL=ON -DJAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
        - RR_CMAKE_GENERATOR="Unix Makefiles"
        
    - os: windows
      before_script:
        - powershell -Command "Set-MpPreference -DisableRealtimeMonitoring 1" || true
        - curl -o boost_1_72_0.zip -L https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip
        - unzip -qo boost_1_72_0.zip
        - cd boost_1_72_0
        - ./bootstrap.bat
        - ./b2 --with-date_time --with-filesystem --with-regex --with-chrono --with-atomic --with-thread --with-random --with-program_options address-model=32 -d0
        - cd $TRAVIS_BUILD_DIR
        - choco install python2 --forceX86
        - /c/Python27/Scripts/pip install numpy
        - /c/Python27/Scripts/pip install setuptools
        - /c/Python27/Scripts/pip install wheel
        - choco install python3 --forceX86 --params "/InstallDir:C:\Python3"
        - /c/Python3/Scripts/pip install numpy
        - /c/Python3/Scripts/pip install setuptools
        - /c/Python3/Scripts/pip install wheel
        - choco install jdk8 --forceX86
        - choco install swig
        - cd $TRAVIS_BUILD_DIR
      env:
        - >
          RR_CMAKE_EXTRA_ARGS="-DBUILD_NET=ON -DBoost_USE_STATIC_LIBS=ON -DBOOST_INCLUDEDIR=$TRAVIS_BUILD_DIR/boost_1_72_0 -DBOOST_LIBRARYDIR=$TRAVIS_BUILD_DIR/boost_1_72_0/stage/lib -DPYTHON_EXECUTABLE=C:/Python27/python.exe -DPYTHON3_EXECUTABLE=C:/Python3/python.exe -DBUILD_PYTHON=ON -DBUILD_PYTHON_WHEEL=ON -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON -DBUILD_JAVA=ON"
        - RR_CMAKE_GENERATOR="Visual Studio 15 2017"
        
    - os: windows      
      before_script:
        - powershell -Command "Set-MpPreference -DisableRealtimeMonitoring 1" || true
        - curl -o boost_1_72_0.zip -L https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.zip
        - unzip -qo boost_1_72_0.zip
        - cd boost_1_72_0
        - ./bootstrap.bat
        - ./b2 --with-date_time --with-filesystem --with-regex --with-chrono --with-atomic --with-thread --with-random --with-program_options address-model=64 -d0
        - cd $TRAVIS_BUILD_DIR
        - choco install python2
        - /c/Python27/Scripts/pip install numpy
        - /c/Python27/Scripts/pip install setuptools
        - /c/Python27/Scripts/pip install wheel
        - choco install python3 --params "/InstallDir:C:\Python3"
        - /c/Python3/Scripts/pip install numpy
        - /c/Python3/Scripts/pip install setuptools
        - /c/Python3/Scripts/pip install wheel
        - choco install jdk8
        - choco install swig
        - cd $TRAVIS_BUILD_DIR
      env:
        - >
          RR_CMAKE_EXTRA_ARGS="-DBUILD_NET=ON -DBoost_USE_STATIC_LIBS=ON -DBOOST_INCLUDEDIR=$TRAVIS_BUILD_DIR/boost_1_72_0 -DBOOST_LIBRARYDIR=$TRAVIS_BUILD_DIR/boost_1_72_0/stage/lib -DPYTHON_EXECUTABLE=C:/Python27/python.exe -DPYTHON3_EXECUTABLE=C:/Python3/python.exe -DBUILD_PYTHON=ON -DBUILD_PYTHON_WHEEL=ON -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON -DBUILD_JAVA=ON"
        - RR_CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
                
    
    - os: osx
      before_script:
        - brew install openssl
        - pip install numpy
        #- brew install boost # Already installed on travis ci image??
        #- brew install swig
        - | 
            (
            rm -rf swig_build_dir
            mkdir -p swig_build_dir
            cd swig_build_dir
            curl -L http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz --output swig-4.0.1.tar.gz
            tar xf swig-4.0.1.tar.gz
            cd swig-4.0.1
            ./configure
            make
            sudo make install
            )
      env:
        - >
          RR_CMAKE_EXTRA_ARGS="-DBUILD_PYTHON=ON -DBUILD_PYTHON_WHEEL=ON -DBUILD_JAVA=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl"
        - RR_CMAKE_GENERATOR="Xcode"
        - RR_CMAKE_TEST_TARGET=RUN_TESTS
        - HOMEBREW_NO_AUTO_UPDATE=1
script:
  - mkdir -p build2
  - cd build2
  - cmake -G "$RR_CMAKE_GENERATOR" -DBUILD_GEN=ON -DBUILD_TEST=ON $RR_CMAKE_EXTRA_ARGS ..
  - cmake --build . --config Release
  - ctest . -C Release --output-on-failure
  - cmake --build . --config Release --target package_source || true
  - mv generated_src out/ || true
  - cp *.tar.gz out/ || true
  - cp *.zip out/ || true
  - cp ../LICENSE.txt out/ || true
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
  - export NOW=`date -u '+%F_%H:%M:%S'`
  - > 
    echo 
    repo: ${TRAVIS_REPO_SLUG},
    job: ${TRAVIS_JOB_NUMBER},
    buildid: ${TRAVIS_BUILD_ID},
    buildurl: ${TRAVIS_JOB_WEB_URL},
    commit: ${TRAVIS_COMMIT},
    tag: ${TRAVIS_TAG},
    osname: ${TRAVIS_OS_NAME},
    cmakegenerator: ${RR_CMAKE_GENERATOR},
    now: ${NOW}
    > out/travis_build_info.txt

before_deploy:
  - cd $TRAVIS_BUILD_DIR/build2
  - tar czf out.tar.gz out

deploy:
  provider: releases
  repo: johnwason/robotraconteur_travisci_deploy
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  deployment_file: true
  file: $TRAVIS_BUILD_DIR/build2/out.tar.gz
  verbose: true
  draft: false
  name: travisci build ${TRAVIS_REPO_SLUG} ${TRAVIS_JOB_NUMBER} ${TRAVIS_BUILD_ID}
  body: |
    repo: ${TRAVIS_REPO_SLUG}
    job: ${TRAVIS_JOB_NUMBER}
    buildid: ${TRAVIS_BUILD_ID}
    buildurl: ${TRAVIS_JOB_WEB_URL}
    commit: ${TRAVIS_COMMIT}
    tag: ${TRAVIS_TAG}
    osname: ${TRAVIS_OS_NAME}
    cmakegenerator: ${RR_CMAKE_GENERATOR}
  on:
    all_branches: true    
    condition: $TRAVIS_BRANCH =~ ^(master|travisci)$
    condition: $TRAVIS_REPO_OWNER =~ ^(robotraconteur|johnwason)$
    condition: "$TRAVIS_REPO_NAME = robotraconteur"
    
    
